name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/hng
          chmod 600 ~/.ssh/hng
          ssh-keygen -y -f ~/.ssh/hng > ~/.ssh/hng.pub || exit 1
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/hng
        shell: bash

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/hng ukpechukwu@34.60.53.38 "
          sudo docker stop fastapi-container || true &&
          sudo docker rm fastapi-container || true &&
          sudo docker pull ***e/fastapi-app:latest &&
          sudo docker run -d --name fastapi-container -p 8000:8000 ***e/fastapi-app:latest
          "
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
