name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ssh_server }}
          username: ${{ secrets.ssh_username }}
          password: ${{ secrets.ssh_password }}
          port: 22
          script: |
            echo "Deploying application..."
            cd /path/to/project

            # Pull latest changes
            git reset --hard HEAD
            git pull origin main

            # Restart the application using Docker Compose
            docker-compose down
            docker-compose up -d --build

            echo "Deployment completed."
