name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t fastapi-app .

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag fastapi-app okaugustine/fastapi-app:latest  # ✅ Ensure username is correct
          docker push okaugustine/fastapi-app:latest

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # ✅ Use GitHub Secret for SSH Key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/hng ukpechukwu@34.60.53.38 "
          sudo docker stop fastapi-container || true &&
          sudo docker rm fastapi-container || true &&
          sudo docker pull okaugustinee/fastapi-app:latest &&
          sudo docker run -d --name fastapi-container -p 8000:8000 okaugustinee/fastapi-app:latest
          "